export {default as Home} from "./Home/Home"
export {default as Shop} from "./Shop/Shop"
export {default as Blog} from "./Blog/Blog"
export {default as Media} from "./Media/Media"
export {default as Features} from "./Features/Features"
export {default as Admin} from "./Admin/Admin"
